2016-07-27 17:42:45,740 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:42:50,845 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:42:53,542 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:42:57,922 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:00,081 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:02,809 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:08,359 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:14,426 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:22,020 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:35,662 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:43:46,671 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:44:02,318 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:44:09,626 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:44:35,527 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:01,310 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:09,678 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:14,281 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:19,634 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:26,188 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:37,243 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:39,554 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:41,186 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:52,487 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:45:57,193 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:46:20,926 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:46:28,729 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:46:30,767 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:46:33,588 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:46:35,258 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:46:45,802 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:06,060 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:13,936 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:25,628 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:33,188 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:37,050 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:39,462 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:47:43,912 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:48:04,951 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:48:15,062 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:48:29,407 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:48:43,501 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:48:49,320 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:48:54,777 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], NULL, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:49:01,151 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], None, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:49:03,099 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], None, people, parent, level));
NameError: global name 'NULL' is not defined
2016-07-27 17:49:05,281 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 36, in spyder
    cur.execute("insert into People_Inf values(%s, %s, %s, %s, %s);", (Title_Section[0], None, people, parent, level));
NameError: global name 'NULL' is not defined
