2016-07-27 08:10:16,607 - __main__ - DEBUG - there is a error
Traceback (most recent call last):
  File "spyder.py", line 39, in spyder
    cur.execute("insert into People_Inf values(?, ?, ?, ?, ?)", (Title_Section[0], Description[0], people, parent, level));
ProgrammingError: syntax error at or near ","
LINE 1: insert into People_Inf values(?, ?, ?, ?, ?)
                                       ^

